"""make_machines_molds_global

Revision ID: 98ee8faef9b9
Revises: 03d7e2648971
Create Date: 2026-03-25 05:14:35.424037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ee8faef9b9'
down_revision: Union[str, None] = '03d7e2648971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'machines', ['code'])
    op.drop_constraint('machines_plan_id_fkey', 'machines', type_='foreignkey')
    op.drop_column('machines', 'plan_id')
    op.create_unique_constraint(None, 'molds', ['code'])
    op.drop_constraint('molds_plan_id_fkey', 'molds', type_='foreignkey')
    op.drop_column('molds', 'plan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('molds', sa.Column('plan_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('molds_plan_id_fkey', 'molds', 'plans', ['plan_id'], ['id'])
    op.drop_constraint(None, 'molds', type_='unique')
    op.add_column('machines', sa.Column('plan_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('machines_plan_id_fkey', 'machines', 'plans', ['plan_id'], ['id'])
    op.drop_constraint(None, 'machines', type_='unique')
    # ### end Alembic commands ###
