"""add lead_time_days and status to components

Revision ID: ffed9e9e75f7
Revises: 98ee8faef9b9
Create Date: 2026-03-26 14:18:34.136582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffed9e9e75f7'
down_revision: Union[str, None] = '98ee8faef9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('lead_time_days', sa.Integer(), nullable=True))
    op.add_column('components', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('components', 'status')
    op.drop_column('components', 'lead_time_days')
    # ### end Alembic commands ###
